export { default } from "./HeroSection";
export { default as ContactForm } from "./ContactForm";
export { default as DasProblemSection } from "./DasProblemSection";
export { default as DerAnsatzSection } from "./DerAnsatzSection";
export { default as DerUnterschiedSection } from "./DerUnterschiedSection";
export { default as SoArbeitenWirSection } from "./SoArbeitenWirSection";
export { default as DreiWegeHomeSection } from "./DreiWegeHomeSection";
export { default as ReferenzenSection } from "./ReferenzenSection";
export { default as WarumSection } from "./WarumSection";
export { default as SchnellcheckSection } from "./SchnellcheckSection";
export { default as CtaSection } from "./CtaSection";
