export { default as HeroSection } from "./HeroSection";
export { default as Differentiation } from "./Differentiation";
export { default as Overview } from "./Overview";
export { default as AdviseSection } from "./AdviseSection";
export { default as ExpertiseSection } from "./ExpertiseSection";
export { default as Partner } from "./Partner";
export { default as ActionSection } from "./ActionSection";
export { default as PodcastSection } from "./PodcastSection";
export { default as WaysSection } from "./WaysSection";
